### ISSUE TITLE
CayenneTester: eager initialization breaks other test tools

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-cayenne#100]
Test setup module produced by `CayenneTester` does eager initialization of `CayenneTesterBootiqueHook`. As with any eager-initialized services, this was bound to cause issues eventually. Just found one recently - using `RmqTester` in the same test as `CayenneTester` doesn't work. Eagerly initialized RMQ stack results in the following exception:

```
java.lang.RuntimeException: Error during initialization of field 'rmq'

at io.bootique.junit5.handler.HandlerUtil.resolveInstance(HandlerUtil.java:39)
at io.bootique.junit5.handler.testtool.GlobalCallbacks.lambda$computeIfAbsent$0(GlobalCallbacks.java:44)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
...
Caused by: java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:142)
at org.testcontainers.containers.RabbitMQContainer.getAmqpPort(RabbitMQContainer.java:107)
at org.testcontainers.containers.RabbitMQContainer.getAmqpUrl(RabbitMQContainer.java:126)
at io.bootique.rabbitmq.junit5.RmqTester.getAmqpUrl(RmqTester.java:53)
at io.bootique.rabbitmq.junit5.tester.TestConnectionFactoryFactory.configureFactory(TestConnectionFactoryFactory.java:42)
at io.bootique.rabbitmq.client.connection.ConnectionFactoryFactory.createConnectionFactory(ConnectionFactoryFactory.java:44)
at io.bootique.rabbitmq.client.RmqObjectsFactory.lambda$createConnectionFactories$4(RmqObjectsFactory.java:125)
at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
at io.bootique.rabbitmq.client.RmqObjectsFactory.createConnectionFactories(RmqObjectsFactory.java:125)
at io.bootique.rabbitmq.client.RmqObjectsFactory.createConnectionManager(RmqObjectsFactory.java:88)
at io.bootique.rabbitmq.client.RabbitMQModule.provideConnectionManager(RabbitMQModule.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at io.bootique.di.spi.ProvidesHandler$ProvidesMethodProvider.get(ProvidesHandler.java:180)
```

I would imagine this can happen with any other test tools that rely on JUnit lifecycle to start. 

A possible solution would be to move test schema initialization to post-startup hook that will be available per #99.

## Upgrade Notes

With the new implementation `ServerRuntime` would be created lazily whenever it is needed in the test code. Any existing code with implicit reliance on eager initialization would fail. E.g. `CayenneTester` schema creation action is run upon ServerRuntime instantiation. So when you use `DbTester` (that knows nothing about CayenneTester), all its operations would fail until ServerRuntime is resolved.

**Comment by andrus** [comment]
Depends on https://github.com/bootique/bootique/issues/322
