### ISSUE TITLE
bootique-cayenne-test presence breaks  BQModuleProviderChecker.testMetadata

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-cayenne#38]
Whenever a module has `bootique-cayenne-test` as one of the test dependencies, it can not execute `BQModuleProviderChecker.testMetadata` test, as Cayenne stack gets eagerly initialized and the following exception is thrown:

```
1) Error injecting constructor, org.apache.cayenne.configuration.server.DataDomainLoadException: [v.4.0.M5 Feb 24 2017 07:47:55] DataDomain startup failed: No DataSources are available for Cayenne. Add a DataSource via 'bootique-jdbc' or map it in Cayenne project.
  at io.bootique.cayenne.test.CayenneTestModule$SchemaLoader.<init>(CayenneTestModule.java:53)
  at io.bootique.cayenne.test.CayenneTestModule.configure(CayenneTestModule.java:34)
  while locating io.bootique.cayenne.test.CayenneTestModule$SchemaLoader
```

**Comment by andrus** [comment]
TODO: retest with JUnit 5 (#78), try new capabilities of JUnit 5 lifecycle
