### ISSUE TITLE
bootique-cayenne-test: test tables are not committed with rollbackOnReturn=true and defaultAutoCommit=false

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-cayenne#44]
With the following test data source settings:

```yaml
jdbc:
  ds:
    url: jdbc:derby:target/derby/derby3;create=true
    initialSize: 1
    rollbackOnReturn: true
    defaultAutoCommit: false
```

created test schema is rolled back and is not visible to the operations that follow:

```java
CayenneTestDataManager dataManager = new CayenneTestDataManager(runtime, false, Table1.class);
Table t1 = dataManager.getTable(Table1.class);
assertEquals(0, t1.getRowCount());
```

```
[main] INFO io.bootique.jdbc.test.DefaultDatabaseChannel - SELECT COUNT(*) FROM "table1"
Stopping all JVM Derby servers...

java.lang.RuntimeException: Error running SQL: SELECT COUNT(*) FROM "table1"

	at io.bootique.jdbc.test.DefaultDatabaseChannel.select(DefaultDatabaseChannel.java:51)
	at io.bootique.jdbc.test.Table.selectOne(Table.java:192)
	at io.bootique.jdbc.test.Table.getRowCount(Table.java:293)
	at io.bootique.cayenne.test.CayenneTestDataManagerTxIT.testDataSourceDoesNotAutocommit(CayenneTestDataManagerTxIT.java:27)
...
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'table1' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
```

**Comment by andrus** [comment]
The fix is in Cayenne - https://github.com/bootique/bootique-cayenne/issues/44  Until it is available, the workaround is to create test datasources with "defaultAutoCommit: true"

**Comment by andrus** [comment]
fixed long ago, as we upgraded to B2.
