### ISSUE TITLE
Default DataSource is not applied when some maps have an explicit one

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-cayenne#69]
Config:

1. An app with multiple Cayenne projects, none of them having Cayenne-defined DataNodes
2. Couple of projects mapped via `CayenneModule.extend(binder).addProject("xyz/cayenne-project.xml"). These should all use a default DataSource.
3. One project that is mapped as a "map" in YAML, and requires a different DataSource.
4. YAML looking like this:

```yml
cayenne:
   datasource: "defaultds"
   maps:
       - name: "x"
          location: "...map.xml"
          datasource: "xdatasource"
```
Not sure I got the config fully right, but the end result is that there's no DataNode created for "defaultds", so projects in item "2" end up without a DataNode, resulting in a startup error like this:

```
Caused by: org.apache.cayenne.CayenneRuntimeException: [v.4.1.B2 May 04 2019 09:30:14] No DataNode configured for DataMap 'xyz' and no default DataNode set
at org.apache.cayenne.access.DataDomain.lookupDataNode(DataDomain.java:485)
at org.apache.cayenne.access.DataDomainQueryAction.engineForDataMap(DataDomainQueryAction.java:532)
at org.apache.cayenne.query.AbstractQuery.route(AbstractQuery.java:116)
at org.apache.cayenne.query.SelectQuery.route(SelectQuery.java:388)
at org.apache.cayenne.query.IndirectQuery.route(IndirectQuery.java:59)
at org.apache.cayenne.access.DataDomainQueryAction.runQuery(DataDomainQueryAction.java:454)
at org.apache.cayenne.access.DataDomainQueryAction.lambda$runQueryInTransaction$1(DataDomainQueryAction.java:437)
```

**Comment by andrus** [comment]
Can't reproduce. See unit tests committed per 1965389d272d2b034d2fa734f9ababf6c117997e
