### ISSUE TITLE
CayenneTester: Better error message when not linked to a BQRuntime

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-cayenne#87]
When CayenneTester is declared, but not linked to any BQRuntimes due to a user error, the error generated is a NPE. Would be great to either have a more specific error indicating what's wrong, or perhaps the tester should do nothing, and print a warning in the logs.

```
java.lang.NullPointerException
at io.bootique.cayenne.v41.junit5.CayenneTester.resolveRuntimeManager(CayenneTester.java:224)
at io.bootique.cayenne.v41.junit5.CayenneTester.lambda$new$0(CayenneTester.java:67)
at io.bootique.cayenne.v41.junit5.tester.CayenneTesterBootiqueHook.lambda$initIfNeeded$0(CayenneTesterBootiqueHook.java:74)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at io.bootique.cayenne.v41.junit5.tester.CayenneTesterBootiqueHook.initIfNeeded(CayenneTesterBootiqueHook.java:74)
at io.bootique.cayenne.v41.junit5.CayenneTester.beforeMethod(CayenneTester.java:242)
at io.bootique.junit5.handler.testtool.Callback.lambda$create$0(Callback.java:50)
at io.bootique.junit5.handler.testtool.CallbackRegistry.beforeEach(CallbackRegistry.java:59)
at io.bootique.junit5.handler.testtool.BQTestToolHandler.beforeEach(BQTestToolHandler.java:46)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:159)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:195)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:195)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:158)
```

**Comment by andrus** [comment]
This got addressed by #98
